### ISSUE TITLE
Fragmenta new not working on windows

### ISSUE THREAD

**Issue by modulor** [fragmenta/fragmenta#10]
i have a problem creating a new cms with fragmenta (windows 10)

"You must create your project in $GOPATH/src"

i'm already in my GOPATH/src 

Please help

**Comment by kennygrant** [comment]
Can you give an example of the path you're using, and the output you get?

**Comment by kefirchik** [comment]
Hi! I have the same issue on Windows 7:
`$GOPATH: C:\homework\go `
```
C:\homework\go\src>%GOPATH%\bin\fragmenta.exe new cms myhomepage
12:33:07 You must create your project in $GOPATH/src
```

**Comment by Draga** [comment]
Hi, same issue here.
At first i thought that it was the capital C but even that didn't help.
I'm trying manually
`println(strings.HasPrefix("C:/dev/go-fragmenta/src/cms", path.Join(os.Getenv("GOPATH"), "src")))`
and that returns true

**Comment by kennygrant** [comment]
I think this must be a windows-specific issue. Unfortunately I don't have easy access to windows to verify,  if anyone can add some logging and run on windows to find out why it is failing that would be useful. Otherwise I'll try to get hold of a test machine and replicate.

**Comment by mycroftsk** [comment]
There is probably bug in `new.go` on `line 42` 

```if !strings.HasPrefix(projectPath, path.Join(os.Getenv("GOPATH"), "src")) {```
and it should be
```if !strings.HasPrefix(projectPath, filepath.Join(os.Getenv("GOPATH"), "src")) {```

Then it will download cms package.

**Comment by amaxcz** [comment]
confirm that, on the windows its fix issue. please update sources.

**Comment by kennygrant** [comment]
I'm looking at updating this week, sorry for the delay on this, I had to get hold of a computer to test on. Pretty sure it is due to the use of path vs filepath as you pointed out but I have a few other instances to check as well.

**Comment by amaxcz** [comment]
but, fragmenta doesnt working on windows now at all.. two big issues, wrong pathnames generated and http library syntax erros... so unable to test it more.

**Comment by kennygrant** [comment]
I have fixed the path issues but still have one issue to look into caused by the lack of a cp command on windows, I have to write this by hand myself using filewalker.

**Comment by TheMangoTrain** [comment]
To anyone having trouble with this. If you get a message "You must create your project in $GOPATH/src" then first check if your $GOPATH is defined. This is seperate from plain old $PATH. Use "echo $GOPATH". If it comes up blank, then you need to deal with that first before exe'ing fragmenta. To set gopath, use: "export GOPATH=$(go env GOPATH)". Confirm with "echo $GOPATH". Worked for me.

**Comment by jksmithiii** [comment]
I had to be explicit with GOPATH. If my GOPATH is set to "c:\gocode," take note of following screen clip. That's as far as I got before getting another issue. cp I think is a linux dependency that doesn't exist on windows.
<img width="398" alt="fragmenta" src="https://cloud.githubusercontent.com/assets/4838263/24623474/1f718dea-186e-11e7-8d34-b354be354979.PNG">

**Comment by kennygrant** [comment]
I have one remaining issue to solve on windows (apologies I haven't had a windows machine for a while). Windows doesn't have a cp command, however I should be able to use filepath.Walk to do something similar just to copy all the files.

**Comment by pakchano** [comment]
A similar problem has occurred to me. 
I am on a macOS Sierra 10.12.5 (16F73). - I'm also new to goLang. 

_However, I solved the issue by setting the $GOPATH to my current working directory._

**Here is the solution:** Note that this is the exact step-by-step process I took to solve this inconvenience. You may want to skip now if you have an idea on how to solve this issue.

```bash
export GOPATH=~/website/my/path
```
Make sure it was set properly, it should give you the same directory:
```bash
echo $GOPATH
```

Then create a new directory called `src` because the error requires that.
So make a new directory with the same name:
```bash
mkdir src
```
then change to that new directory:
```
cd src
```

And finally you can use fragmenta.
```bash
fragmenta new cms my-fragmenta-cms
```

**Note that _fragmenta_'s alias had to be setup manually too.**
Go to the `.zshrc` and/or `.bash_profile`, or your preferred _bash_

And add a couple of new lines:
```bash
# alias to fragmenta/fragmenta cms
alias fragmenta="$HOME/go/bin/fragmenta"
```

Hope this helps someone out there. Cheers!

**Comment by wscheffer** [comment]
@kennygrant So I managed to fix a bunch of the windows issues, but I'm constantly running into an issue where the `.json` files aren't being created for example `secrets/fragmenta.json` and `secrets/assets.json` not sure what I'm missing

**Comment by kennygrant** [comment]
Should now be fixed. Please let me know if you still see any issues.
