### ISSUE TITLE
Fragmenta new  Error writing config /root/fragmentaCms/src/secrets/fragmenta.json

### ISSUE THREAD

**Issue by StefanoChiodino** [fragmenta/fragmenta#12]
Trying to install fragmenta cms

```
./fragmenta new cms /root/fragmentaCms/src
14:42:50 Fetching from url: github.com/fragmenta/fragmenta-cms
14:43:21 Creating files at: /root/fragmentaCms/src
14:43:21 Removing all at:/root/fragmentaCms/src/.git
14:43:21 Initialising new git repo at:/root/fragmentaCms/src
14:43:21 Updating import paths to: /root/fragmentaCms/src
14:43:22 Generating new config at /root/fragmentaCms/src/secrets/fragmenta.json
14:43:22 Error writing config /root/fragmentaCms/src/secrets/fragmenta.json open /root/fragmentaCms/src/secrets/fragmenta.json: no such file or directory
14:43:22 Error generating config open /root/fragmentaCms/src/secrets/fragmenta.json: no such file or directory
```

**Comment by kennygrant** [comment]
What do you get if you ls /root/fragmentaCms/src

**Comment by kennygrant** [comment]
Should now be fixed, thanks for reporting.

**Comment by VagelisProkopiou** [comment]
Same error:
`Generating new config at /home/va/projects/fragmentaSite/src/secrets/fragmenta.json
Error writing config /home/va/projects/fragmentaSite/src/secrets/fragmenta.json open /home/va/projects/fragmentaSite/src/secrets/fragmenta.json: no such file or directory
Error generating config open /home/va/projects/fragmentaSite/src/secrets/fragmenta.json: no such file or directory`

OS: Debian 8

GO version: go1.8 linux/amd64

GOPATH=/home/va/projects/fragmentaSite

**Comment by kennygrant** [comment]
@VagelisProkopiou your gopath should not be set to the site folder. GOPATH is for all your go code, not just a per-project path.

**Comment by VagelisProkopiou** [comment]
Thanx @kennygrant. I reverted the GOPATH to my default ( /home/va/go), but the installation fails with the same error.

It seems that the GOPATH actual destination is irrelevant (at least in my case). Though it seems quite straightforward, I can't make it work.

Any suggestions are welcome.
