### ISSUE TITLE
How do you setup psql for fragmenta?

### ISSUE THREAD

**Issue by qarth** [fragmenta/fragmenta#14]
Hey,

I get the following error when trying to run migrate and server respectively:

```
06:05:56 ERROR loading sql migration:exit status 2
06:05:56 All further migrations cancelled

06:05:56 No migrations to perform at path ./db/migrate
```

server
`2017/03/25 06:06:08 Error reading database pq: database "topo_development" does not exist`

Do I need to migrate manually and initialise the users with the secrets\fragmenta.json passwords? 
Are those generated passwords already hashed by something?
Would I use the createuser -P -s  -e  fragmenta_server command?

Tried everything, read your docs, read psql docs, pretty frustrated.. first time psql user.
Thanks

**Comment by qarth** [comment]
in your code: 			```
```
// Execute this sql file against the database
			result, err := runCommand("psql", args...)
```

```
consider using sql package instead of this hack

Hence the current user need to have all permissions in psql in a database named $USER and account $USER must indeed exist.

add this to your readme:
sudo su postgres
createuser $USER
psql
ALTER USER $USER WITH SUPERUSER;
ALTER USER $USER WITH CREATEROLE;
ALTER USER $USER WITH CREATEDB;

#Check user priveleges with \du
\q
exit

fragmenta migrate

**Comment by qarth** [comment]
Please find the time to upgrade fragmenta.eu before others waste hours on this

**Comment by kennygrant** [comment]
I'm looking at the new setup just now, will see if I can address this too. 

I did assume you have a separate superuser you can run migrations with, as otherwise they won't be able to create a database and create the initial db user (as set up in the secrets file), but db access has been a persistent sticking point for new users.

**Comment by kennygrant** [comment]
Thanks and sorry it took me so long to update the readme, I've inserted your instructions. 

I also want to address the use of the psql binary to perform migrations, but there is a problem with that as bootstrapping will always require privileges to create users/dbs, I guess it'll have to special case bootstrapping. See issue #1.
