### ISSUE TITLE
windows 10 website creation

### ISSUE THREAD

**Issue by jksmithiii** [fragmenta/fragmenta#16]
<img width="398" alt="fragmenta" src="https://cloud.githubusercontent.com/assets/4838263/24572148/ddbb974e-163b-11e7-907f-8c8f9a239f90.PNG">

**Comment by jksmithiii** [comment]
Ok, apparently a known issue in new.go and got past that with some recursive copydir code I found on github. No further obvious issues running fragmenta app.

**Comment by kennygrant** [comment]
Thanks for reporting. I need to do some testing on windows and rewrite this code which relies on cp which is not available there. This is a dupe of #10 so closing this one.
