### ISSUE TITLE
Use GOPATH instead of absolute path

### ISSUE THREAD

**Issue by tuxlinuxien** [fragmenta/fragmenta#2]
I have started playing with fragmenta and when I try to use `fragmenta server`, I have errors like this:

```
src/app/setup.go:13:2: import "/home/yoann/work/fragmenta/my/site/src/lib/authorise": cannot import absolute path
src/app/routes.go:7:2: import "/home/yoann/work/fragmenta/my/site/src/pages/actions": cannot import absolute path
src/app/routes.go:4:2: import "/home/yoann/work/fragmenta/my/site/src/posts/actions": cannot import absolute path
src/app/routes.go:8:2: import "/home/yoann/work/fragmenta/my/site/src/tags/actions": cannot import absolute path
src/app/routes.go:9:2: import "/home/yoann/work/fragmenta/my/site/src/users/actions": cannot import absolute path
```

Is it possible to generate files that use GOPATH variable?

**Comment by kennygrant** [comment]
It currently expects your project to be within GOPATH/src as go prefers that for builds. Which path did you give the new command, and what is the value of your GOPATH at present?

**Comment by tuxlinuxien** [comment]
```
$> export GOPATH=/home/yoann/work/fragmenta/my/site/
```

but the import path of my generated files is `/home/yoann/work/fragmenta/my/site/src/lib/authorise` instead of `lib/authorise`

**Comment by kennygrant** [comment]
Hi, GOPATH is intended to be the place where all your go projects live, it takes a little getting used to, but  it would be worth looking at this article for ref: https://golang.org/doc/code.html

GOPATH should contain - 

bin for binaries
pkg for build artefacts
src for source code (which can be many projects, and is arranged be repo url). 

So, your GOPATH should probably be /home/yoann/work/ or /home/yoann/work/go or something lilke that, and should be set in your .profile file or similar (see instructions above). 

Then to make a site, cd to that directory, and use fragmenta new cms github.com/tuxlinuxien/mysitename

or something like that. Now *within* that project dir you'll then find a bin (for server binaries, src for src etc), and your import paths should be of the form "github.com/tuxlinuxien/mysitename/src/users" and   "github.com/tuxlinuxien/mysitename/src/lib/authorise" (so relative to GOPATH). If that is breaking for you though, let me know the command you used to create a new site. It does attempt to take into account GOPATH and expects your sites to be within GOPATH/src, so if they are not it might break. I suspect that is what happened here?

**Comment by tuxlinuxien** [comment]
hi,

I got it, I see when I did the mistake with my GOPATH.

Thx for the reply.
