### ISSUE TITLE
fragmenta: command not found

### ISSUE THREAD

**Issue by rebootcode** [fragmenta/fragmenta#20]
I have go 1.8.3 in Ubuntu 16.04 and i ran 2 command below :- 

`go get -u github.com/fragmenta/fragmenta`

then
`fragmenta new cms blog`

and i got the error `fragmenta: command not found`

**Comment by kennygrant** [comment]
Sounds like the fragmenta command is not in your path (either didn't build or your gopath/bin is not in your path). If you do echo $PATH what do you see?

**Comment by rebootcode** [comment]
I just echo `$PATH` and found golang "bin" directory is not in my path list. I just added them and it works fine now.

Thanks

**Comment by rafaelmagalhaes** [comment]
Hi i'm having same issue but i have go in $PATH

`IGHQ-ST05:~ rafael$ go version
go version go1.9.2 darwin/amd64
IGHQ-ST05:~ rafael$ go evn
go: unknown subcommand "evn"
Run 'go help' for usage.
IGHQ-ST05:~ rafael$ go env
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/rafael/Documents/go"
GORACE=""
GOROOT="/usr/local/go"
GOTOOLDIR="/usr/local/go/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/5h/tb6lmfq92hl4jyf1gkg1gg54p39ctf/T/go-build282141787=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"`
