### ISSUE TITLE
How to Setup Domain and Run via Document Root

### ISSUE THREAD

**Issue by rebootcode** [fragmenta/fragmenta#21]
I have vestaCP panel installed. I have added the domain to my vestaCP. Domain serves document from

`/home/user/web/example.com/public_html`

How can I serve file from above path and run on domain added using fragmenta.

**Comment by kennygrant** [comment]
I'm afraid this is a question about Vesta more than about fragmenta. From this tutorial, it looks like Vesta installs nginx:

https://www.digitalocean.com/community/tutorials/how-to-install-vestacp-and-set-up-a-website-on-ubuntu-14-04

If that's the case, you need nginx to function as a proxy in front of a go serivce. I'd run your go app as a service using systemd or similar on a high port (say 3001), and then proxy it with nginx (this will require editing nginx configs). Something like this:

https://www.digitalocean.com/community/tutorials/how-to-configure-nginx-with-ssl-as-a-reverse-proxy-for-jenkins

You may not be able to use letsecrypt with that setup.
