### ISSUE TITLE
Use gofmt during development

### ISSUE THREAD

**Issue by cgchoffman** [fragmenta/fragmenta#25]
I'm trying to get my PR together and I'm finding a bunch of changes that I didn't think I had made.  It didn't take long to realize it's that I have my editor setup to `gofmt` on save so it's changing things.

Using *gofmt* is standard in Go development as far as I know.  It would be a good idea to start using that or more people trying to contribute will hit this..  I know it almost made me throw away my PR because I have to go through all my code and revert a bunch of changes before I can make the commit.

Also, I know this isn't a bug.  I can't find where I'm supposed to reach out to the devs on this project.  The docs just say "reach out if you want to help" but there is no contact info.  I'm sure I could find it if I did some sleuthing but I have other things to do today :)

**Comment by kennygrant** [comment]
I do use gofmt when saving, I think this arose because the file you looked at (new.go) was recently changed by a pull request, and I merged it without resaving the file.
