### ISSUE TITLE
 fragmenta: command not found

### ISSUE THREAD

**Issue by daslicht** [fragmenta/fragmenta#29]
```
$ go get -v -u github.com/fragmenta/fragmenta 
github.com/fragmenta/fragmenta (download)
github.com/fragmenta/assets (download)
github.com/fragmenta/query (download)
github.com/go-sql-driver/mysql (download)
github.com/lib/pq (download)
$ fragmenta
-bash: fragmenta: command not found

```
```go version go1.10.2 darwin/amd64```

What's wrong please?

**Comment by Hamidumi** [comment]
try
`sudo ln -s $GOPATH/bin/* /usr/bin`

**Comment by kennygrant** [comment]
You need installed binaries in your path, so either add GOPATH/bin to your path, or use the command above to make a symlink into /usr/bin (which is already in your path) for any compiled go binaries from GOPATH.
