### ISSUE TITLE
Error writing config file on Linux

### ISSUE THREAD

**Issue by tuxlinuxien** [fragmenta/fragmenta#3]
when i run fragmenta to generate a new cms env, here is the output that I have

```
%> fragmenta new cms my/path/   
20:45:06 
20:45:06 Error copying site exit status 1
20:45:06 Error copying project exit status 1
```

is there a way to make it more verbose?

**Comment by kennygrant** [comment]
Sorry for the delay in responding. At present no there's no way to control verbosity. Are you on Windows? There is a problem copying files on windows I think, as we assume a unix (linux/os x).

**Comment by tuxlinuxien** [comment]
I am running this command on linux (Xubuntu 15.10). I am a actually in china, so I thought it was because of the Great Firewall but even with a VPN, I still have this problem.

**Comment by kennygrant** [comment]
It does a git checkout of a repo from github, so that might be the issue. I will look at error reporting if that fails so that at least we report the error properly. Perhaps the blank line is supposed to contain an error.

**Comment by kennygrant** [comment]
I have improved error handling a little, and checked that it gives you an error if there is a failure in go get, which it does (e.g. if no network or bad network). You can also get the cms package first by fetching it, and then go get will use the local copy without hitting the network. 

However I suspect your problem lies elsewhere. If you can try again now and let me know that would be useful.

**Comment by tuxlinuxien** [comment]
```
yoann:/home/yoann/toto/src% fragmenta new cms my/path/here
17:51:38 Fetching from url: github.com/fragmenta/fragmenta-cms
17:56:57 Creating files at: /home/yoann/toto/src/my/path/here
17:56:57 Removing all at:/home/yoann/toto/src/my/path/here/.git
17:56:57 Initialising new git repo at:/home/yoann/toto/src/my/path/here
17:56:57 Updating import paths to: my/path/here
17:56:57 Generating new config at /home/yoann/toto/src/my/path/here/secrets/fragmenta.json
17:56:57 Error writing config /home/yoann/toto/src/my/path/here/secrets/fragmenta.json open /home/yoann/toto/src/my/path/here/secrets/fragmenta.json: no such file or directory
17:56:57 Error generating config open /home/yoann/toto/src/my/path/here/secrets/fragmenta.json: no such file or directory
```
Here are my errors

**Comment by kennygrant** [comment]
When you run this test, can you check what you see in the following paths:

/home/yoann/toto/src/my/path/here
/home/yoann/toto/src/my/path/here/secrets
$GOPATH/src/fragmenta/fragmenta-cms

do you see a folder at /home/yoann/toto/src/my/path/here/secrets or is there nothing there? The error appears to be that this folder doesn't exist. The other possibility is that you don't have permissions to write to it. When I test here with fresh files it all works ok (testing on OS X). 

Also, I assume you're on the latest fragmenta, and have deleted $GOPATH/src/fragmenta/fragmenta-cms ? (it appears so from the errors reported above).

**Comment by kennygrant** [comment]
This issue appears to be linux specific and related to the copy of the reference repo, which is being copied to the target + fragmenta-cms rather than just the target dir on linux.

**Comment by kennygrant** [comment]
This should now be fixed, please try go get -u github.com/fragmenta/fragmenta and try again.
