### ISSUE TITLE
Create fullpath when I use fragment pose $GOPATH/src

### ISSUE THREAD

**Issue by SebastianPozoga** [fragmenta/fragmenta#8]
When i created project in wrong path ~/dev/ (outside my $GOPATH) it don't put any error and create project incorrectly.

When I try run it i take an error:
`import "/Users/...": cannot import absolute path`

**Comment by kennygrant** [comment]
Yes, definitely need a better error message in this case, as people new to go are not familiar with the gopath restriction, and we just assume you are in the go path.

**Comment by kennygrant** [comment]
Closed and merged pull request. Thanks.
